det <- read.table("SPR.txt",header=TRUE, colClasses = c("factor", "numeric", "numeric", "factor", "numeric", "factor", "factor"))
det$RunDate <- factor(det$RunDate,
                      labels = c("25/11/2008","27/11/2008", "3/12/2008", "5/12/2008", "8/12/2008"))

plot(det, panel=panel.smooth)
summary(det)
barplot(tapply(det$Response,list(det$EnzymeConc, det$Enzyme),mean),beside=TRUE)
par(mfrow=c(2,1),mar=c(3,3,2,1),mgp=c(2,0.7,0))
boxplot(Response ~ EnzymeConc,det)
boxplot(Response ~ Enzyme, det)

par(mfrow=c(2,2))
lm1 <- lm(Response ~ RunDate+Cycle+Enzyme*EnzymeConc*DetStock*CaStock, det)
summary(lm1)
plot(lm1)
anova(lm1)
lm2 <- step(lm1)
summary(lm2)
anova(lm2)
drop1(lm2, test="F")

det$logR <- log(det$Response)
lm3<- step(lm(logR ~ RunDate+Cycle+Enzyme*EnzymeConc*DetStock*CaStock, det, subset = -14))
par(mfrow=c(2,2))
plot(lm3)
summary(lm3)
anova(lm3)
AIC(lm3)
drop1(lm3, test="F")
coef(lm3)

plot(det$EnzymeConc, exp(det$logR), col=as.numeric(det$EnzymeA), pch=19)
interaction.plot(det$EnzymeConc, det$Enzyme, exp(det$logR), ylim = c(0,1500))